### PR TITLE
[Silicon Labs] Update board IDs

### PR DESCRIPTION
**Pull request by stevew817**
Updated board IDs for Silicon Labs targets.

### CODE REVIEW

**Comment by screamerbg** [comment]
We are aligned with Steven

**Comment by stevew817** [comment]
@bridadan These targets aren't public yet, which is why we can get away with renaming them :)

**Comment by stevew817** [comment]
@bridadan ARMmbed/mbed-os#4059 got merged, so this one should probably merge as well?

**Comment by bridadan** [comment]
@stevew817 Fine with me, but I don't have merge powers :smile: That's up to @mazimkhan or @adbridge.

**Pull request merged**
