### PR TITLE
Add FreeBSD support

### PR DESCRIPTION
**Pull request by evadot**
We get the device by looking at the exported sysctls that describe the devices.

Signed-off-by: Emmanuel Vadot <manu@bidouilliste.com>

### CODE REVIEW

**Comment by bridadan** [comment]
Hi @evadot, thanks very much for your contribution.

It looks like the `sysctl` pip package is only valid for FreeBSD systems, however our CI system runs on Linux (hence the broken build). After doing a little research, it may be possible for you to mark the dependency as conditional by using "Environment Markers" as described here: https://www.python.org/dev/peps/pep-0496/

Let me know if you have any other questions!

**Comment by evadot** [comment]
> Hi @evadot, thanks very much for your contribution.
> 
> It looks like the `sysctl` pip package is only valid for FreeBSD systems, however our CI system runs on Linux (hence the broken build). 

 Yeah I saw that too, I though it was available everywhere ...

> After doing a little research, it may be possible for you to mark the dependency as conditional by using "Environment Markers" as described here: https://www.python.org/dev/peps/pep-0496/

 This PEP seems rejected but I'll see what I can find.

> Let me know if you have any other questions!

Thanks

**Comment by bridadan** [comment]
Hi @evadot, have you had a chance to look at this? We have no issue leaving this open, just wondering if we can help it along in some way!

**Comment by evadot** [comment]
Sorry I had no time to work on this recently, maybe this week.

**Comment by bridadan** [comment]
Hello from the new year @evadot! I'm doing some GitHub issues/pr maintenance today. Are you still interested in working on this?

**Comment by bridadan** [comment]
Hi @evadot, we're moving this repo (see https://github.com/ARMmbed/mbed-ls/pull/415 for more info). I'm going to close this PR for now, however if you feel like pursuing this further feel free to reopen it in the new repo!

**Pull request closed without merging**
