### PR TITLE
Add KL27Z, KL43Z and K66F to the list of boards

### PR DESCRIPTION
**Pull request by mmahadevan108**
Signed-off-by: Mahadevan Mahesh <Mahesh.Mahadevan@nxp.com>

### CODE REVIEW

**Comment by mmahadevan108** [comment]
Test results below: 
c:\cygwin\home\r9aadq\my_mbed>mbedls
+---------------+----------------------+-------------+-------------+--------------------------------------------------+-----------------+
| platform_name | platform_name_unique | mount_point | serial_port | target_id                                        | daplink_version |
+---------------+----------------------+-------------+-------------+--------------------------------------------------+-----------------+
| KL43Z         | KL43Z[0]             | D:          | COM17       | 0262000026334e45002d400e5ebb00311141000097969900 | 0241            |
+---------------+----------------------+-------------+-------------+--------------------------------------------------+-----------------+

c:\cygwin\home\r9aadq\my_mbed>mbedls
+---------------+----------------------+-------------+-------------+--------------------------------------------------+-----------------+
| platform_name | platform_name_unique | mount_point | serial_port | target_id                                        | daplink_version |
+---------------+----------------------+-------------+-------------+--------------------------------------------------+-----------------+
| K66F          | K66F[0]              | D:          | COM18       | 0311000034544e45003400048e3800095a91000097969900 | 0241            |
+---------------+----------------------+-------------+-------------+--------------------------------------------------+-----------------+

c:\cygwin\home\r9aadq\my_mbed>mbedls
+---------------+----------------------+-------------+-------------+--------------------------------------------------+-----------------+
| platform_name | platform_name_unique | mount_point | serial_port | target_id                                        | daplink_version |
+---------------+----------------------+-------------+-------------+--------------------------------------------------+-----------------+
| KL27Z         | KL27Z[0]             | D:          | COM9        | 0261000026284e45000a900666a4001bcca1000097969900 | 0241            |
+---------------+----------------------+-------------+-------------+--------------------------------------------------+-----------------+

**Comment by mmahadevan108** [comment]
@bridadan @maclobdell

**Comment by bridadan** [comment]
The platform IDs match up for the KL27Z and KL43Z on the website, but I don't see K66F on the website. Any idea at @sg- or @maclobdell ? And should the K66F ID lead with a `02` instead of `03` to fit with the rest of the FRDM boards?

Otherwise changes seem fine to me.

**Comment by mmahadevan108** [comment]
cc @flit

**Comment by mmahadevan108** [comment]
Here is a list I had received from Mac:
FRDM-K66F	311
FRDM-KL82Z   none assigned yet
FRDM-K82F     none assigned yet
FRDM-KW41Z none assigned yet

**Comment by maclobdell** [comment]
Per previous agreement, the board ID for FRDM-K66F is 0311.  I have added this platform and created the platform page template at https://developer.mbed.org/platforms/FRDM-K66F/  (Private to NXP group right now)

**Comment by bridadan** [comment]
Thanks @maclobdell! LGTM :+1:

**Comment by mmahadevan108** [comment]
Can this be merged?

**Pull request merged**
