### PR TITLE
[ST] add 3 new platforms : NUCLEO_F439ZI, NUCLEO_F756ZG, NUCLEO_L486RG

### PR DESCRIPTION
**Pull request by adustm**

### CODE REVIEW

**Comment by mazimkhan** [comment]
@screamerbg Can you please check?

**Comment by adustm** [comment]
Hello, @screamerbg, any news ?
Kind regards
Armelle

**Comment by mazimkhan** [comment]
@maclobdell can you please confirm this change.

**Comment by screamerbg** [comment]
IDs are correct!

**Pull request merged**
