### PR TITLE
Change LPC54608 to LPC546XX to include support for LPC54608/18/28

### PR DESCRIPTION
**Pull request by mmahadevan108**
Signed-off-by: Mahadevan Mahesh <Mahesh.Mahadevan@nxp.com>

### CODE REVIEW

**Comment by mmahadevan108** [comment]
cc @0xc0170 @theotherjimmy @maclobdell

**Comment by theotherjimmy** [comment]
Hmmmm.... So if I plug in a LPC54608, and try to run `mbed compile -m detect -t <whatever>` what would this do?

**Comment by mmahadevan108** [comment]
Below is what you will see.
____________________________
PS C:\cygwin\home\r9aadq\my_mbed> mbed test --compile -t GCC_ARM -m detect
[mbed] Detected "LPC546XX" connected to "D:" and using com port "COM57"
WARNING: MBED_GCC_ARM_PATH set as environment variable but doesn't exist
Building library mbed-build (LPC546XX, GCC_ARM)
Scan: my_mbed
Copy: mbed.h
Copy: arm_math.h
Copy: core_armv8mbl.h
Copy: core_armv8mml.h
_______________________________

**Comment by theotherjimmy** [comment]
I added a merge commit. Don't worry about the merge commits too much. This is not mbed-os 😉

**Comment by theotherjimmy** [comment]
@mmahadevan108 That output looks great!

@maclobdell Could you confirm the device id's for me?

**Comment by mmahadevan108** [comment]
@maclobdell @theotherjimmy Can this change be integrated?

**Comment by mmahadevan108** [comment]
@maclobdell @theotherjimmy. I have rebased this patch to resolve merge conflicts. I have readded LPC54114 and LPC54608.

**Comment by maclobdell** [comment]
the IDs match our system.  Looks good to me.

**Comment by maclobdell** [comment]
Please put high priority on this one.  Please merge and release in time for mbed OS 5.6.2.

**Comment by theotherjimmy** [comment]
Give me a moment. I'm making a release series branch, as I'm not yet confidant in master.

**Pull request merged**
