### PR TITLE
Rename DISCO_L496G

### PR DESCRIPTION
**Pull request by bcostm**
Rename this platform DISCO_L496AG following our naming convention.

### CODE REVIEW

**Comment by bridadan** [comment]
Still waiting on Mbed DB. Just making sure this doesn't get left behind!

@bcostm do you have the information/contact details to get this updated?

**Comment by bcostm** [comment]
> do you have the information/contact details to get this updated?

What do you mean exactly ?

**Comment by bridadan** [comment]
@bcostm I meant do you know who to contact within Arm to get the DB updated? I'm pretty sure the right people would be @screamerbg and @maclobdell.

**Comment by bcostm** [comment]
Ha OK... My primary contact at ARM is @screamerbg

**Comment by screamerbg** [comment]
@bridadan the name in the Mbed website database is now changed to DISCO_L496AG

**Comment by jeromecoutant** [comment]
Maybe we can release this one ?

Thx

**Comment by bridadan** [comment]
@jeromecoutant Version 1.4.1 has been released!

**Pull request merged**
