### PR TITLE
Use PrettyTable with GitHub policy

### PR DESCRIPTION
**Pull request by jeromecoutant**
This is following https://github.com/ARMmbed/greentea/issues/277 discussion

### CODE REVIEW

**Comment by jeromecoutant** [comment]
For information, here is all related PR :

- https://github.com/ARMmbed/mbed-os/pull/7720
- https://github.com/ARMmbed/greentea/pull/279
- https://github.com/ARMmbed/mbed-ls/pull/383
- https://github.com/ARMmbed/htrun/pull/208

**Comment by bridadan** [comment]
Just to have before and after, the output has changed from:

**console**

```
+---------------+----------------------+------------------------------------------------+--------------+--------------------------+-----------------+
| platform_name | platform_name_unique | mount_point                                    | serial_port  | target_id                | daplink_version |
+---------------+----------------------+------------------------------------------------+--------------+--------------------------+-----------------+
| NUCLEO_F411RE | NUCLEO_F411RE[0]     | /mnt/pci-0000_00_06_0-usb-0_2_1_1-scsi-0_0_0_0 | /dev/ttyACM0 | 07400221076061193824F764 | 0221            |
+---------------+----------------------+------------------------------------------------+--------------+--------------------------+-----------------+
```

**rendered**

+---------------+----------------------+------------------------------------------------+--------------+--------------------------+-----------------+
| platform_name | platform_name_unique | mount_point                                    | serial_port  | target_id                | daplink_version |
+---------------+----------------------+------------------------------------------------+--------------+--------------------------+-----------------+
| NUCLEO_F411RE | NUCLEO_F411RE[0]     | /mnt/pci-0000_00_06_0-usb-0_2_1_1-scsi-0_0_0_0 | /dev/ttyACM0 | 07400221076061193824F764 | 0221            |
+---------------+----------------------+------------------------------------------------+--------------+--------------------------+-----------------+

to:

**console**

```
| platform_name | platform_name_unique | mount_point                                    | serial_port  | target_id                | daplink_version |
|---------------|----------------------|------------------------------------------------|--------------|--------------------------|-----------------|
| NUCLEO_F411RE | NUCLEO_F411RE[0]     | /mnt/pci-0000_00_06_0-usb-0_2_1_1-scsi-0_0_0_0 | /dev/ttyACM0 | 07400221076061193824F764 | 0221            |
```

**rendered**

| platform_name | platform_name_unique | mount_point                                    | serial_port  | target_id                | daplink_version |
|---------------|----------------------|------------------------------------------------|--------------|--------------------------|-----------------|
| NUCLEO_F411RE | NUCLEO_F411RE[0]     | /mnt/pci-0000_00_06_0-usb-0_2_1_1-scsi-0_0_0_0 | /dev/ttyACM0 | 07400221076061193824F764 | 0221            |

**Comment by bridadan** [comment]
@theotherjimmy if any of the prs @jeromecoutant mentioned come in, we should probably merge this at the same time for consistency.

**Comment by jeromecoutant** [comment]
Hi
For information, this is not in a released version. Is it planned ?
Thx

**Comment by bridadan** [comment]
Hi @jeromecoutant, this was released in 1.6.0!

**Comment by jeromecoutant** [comment]
OK, sorry, I have only checked the github label (as for mbed-os)
Thx

**Pull request merged**
