### PR TITLE
Add NUCLEO_F746ZG ID

### PR DESCRIPTION
**Pull request by bcostm**

### CODE REVIEW

**Comment by PrzemekWirkus** [comment]
@sg- Please check if this is valid ID from your pov. so I can merge. Thanks!

**Comment by PrzemekWirkus** [comment]
@screamerbg MIhail, can you check this ID before we merge and release mbed-ls.
I think Sam is not available?

**Comment by sg-** [comment]
👍

**Comment by PrzemekWirkus** [comment]
@bcostm Released to PyPI, you can use `pip install mbed-ls -U` to get latest mbed-ls :)

**Pull request merged**
