### PR TITLE
Fixed NUMAKER_PFM_NUC472's ID

### PR DESCRIPTION
**Pull request by screamerbg**
NUMBED no longer exist and is replaced by NUMAKER_PFM_NUC472

### CODE REVIEW

**Comment by PrzemekWirkus** [comment]
So 1301 and 1302 are the same platform?

**Comment by screamerbg** [comment]
@PrzemekWirkus I guess so. I have the final product with me (test results here https://github.com/ARMmbed/mbed-os/pull/2238#issuecomment-237519745) and the ID is 1301, not 1302.

**Comment by screamerbg** [comment]
@PrzemekWirkus please don't merge yet. Would like to confirm with Nuvoton.

cc @ccli8

**Comment by PrzemekWirkus** [comment]
@screamerbg I thiink @mazimkhan will merge and release mbed-ls from now on! Wish him luck.
I think this and other PR can be merged and released under v1.2.**1**.

**Comment by cyliangtw** [comment]
I am Nuvoton mbed task leader. Because NUMBED 1301 has trademark concern, we revised the board name and applied 1302 for NUMAKER_PFM_NUC472, 1303 for NUMAKER_PFM_M453. It's better to keep 1301 for NUMBED. If you want to get 1302 on your board with old board name "Nu-mbed-NUC472", just to upgrade ICE firmware. Moreover, we also sent 10 pcs with revised board name & new ICE firmware to Eric Yang for UK or US team, I explained it to Sam Grove in ARMmbed/mbed-os#2238.

**Comment by mazimkhan** [comment]
@screamerbg can you please react to the above comment.

**Comment by screamerbg** [comment]
@cyliangtw thanks for the explanation

**Pull request closed without merging**
