### PR TITLE
Add NUCLEO_H743ZI and NUCLEO_F722ZE

### PR DESCRIPTION
**Pull request by ohagendorf**
adding two new manufacture ids for NUCLEO_H743ZI and NUCLEO_F722ZE

### CODE REVIEW

**Comment by theotherjimmy** [comment]
@ohagendorf I have restarted the Travis CI job, as it appeared to be a spurious failure.

**Comment by theotherjimmy** [comment]
@maclobdell Could you confirm these device numbers for me?

**Comment by maclobdell** [comment]
The IDs match the system, however @screamerbg should provide final confirmation.

**Comment by ohagendorf** [comment]
I rebased it.

**Comment by theotherjimmy** [comment]
Thanks for the rebase @ohagendorf 

Still waiting on @screamerbg to provide final confirmation.

**Comment by ohagendorf** [comment]
I rebased it.

**Pull request closed without merging**
