### PR TITLE
Add MTB_ADV_WISE_1530

### PR DESCRIPTION
**Pull request by KariHaapalehto**

### CODE REVIEW

**Comment by KariHaapalehto** [comment]
@ashok-rao Please review

**Comment by ashok-rao** [comment]
PE platform database updated with board ID = 0459 for WISE 1530. Slug not updated since no platform page..
@bridadan @theotherjimmy .. could you please review / merge if all OK? Thanks..!

**Comment by theotherjimmy** [comment]
Waiting on travis.

**Comment by theotherjimmy** [comment]
Sorry guys, I goofed up the merge. Just a sec

**Pull request merged**
