### PR TITLE
Add support for Nuvoton NUC472 NuTiny

### PR DESCRIPTION
**Pull request by ccli8**

### CODE REVIEW

**Comment by ccli8** [comment]
Hi,
I'd like to add target ID of Nuvoton NUC472 NuTiny board into lstools_base.py, but meet CircleCI check error which I could not fix. Could you help clarify it?
"1235": "UBLOX_C027",
**"1300": "NUC472-NUTINY",**
"1549": "LPC1549",

**Comment by PrzemekWirkus** [comment]
@ccli8 I think I can't do this. All this mappings are assigned by our partner enablement team. I can only add this if I get a internal info that this is correct mapping to valid name we will be using.
I do not know if you are our partner or not but like I said I can't just add mapping like this. It is a formal process because Target ID mapping is assigned by us (mbed) to proper partners (just like MAC pools are assigned to particular vendors).

**Comment by ccli8** [comment]
@PrzemekWirkus Nuvoton is a partner of ARM mbed. The ID to merge in is assigned by Sam.Grove@arm.com.

**Comment by PrzemekWirkus** [comment]
@sg- Sam, when you are back from holiday please let me know if we can merge it.

**Comment by sg-** [comment]
good to merge!

**Pull request merged**
