### PR TITLE
Show unknown boards/devices in bootloader mode

### LINKED ISSUE #235: DAPLink devices in bootloader mode are no longer detected
DAPLink CI is broken since devices in bootloader mode are no longer detected. This worked in 1.2.14 but is broken in 1.3.1.

mbed-ls (1.3.1)
---
```
> mbedls -d
DEBUG:mbedls.main:mbed-ls ver. 1.3.1
DEBUG:mbedls.main:host: ('nt', 'Windows', '10', '10.0.14393', 'win32')
WARNING:root:Could not read htm on from usb id 0000000033514e45001c500585d40025e981000097969900. Falling back to usb id
```

mbed-ls (1.2.14)
---
```
> mbedls
+---------------+----------------------+-------------+-------------+--------------------------------------------------+-----------------+
| platform_name | platform_name_unique | mount_point | serial_port | target_id                                        | daplink_version |
+---------------+----------------------+-------------+-------------+--------------------------------------------------+-----------------+
| unknown       | None[0]              | D:          | unknown     | 0000000033514e45001c500585d40025e981000097969900 | 0244            |
+---------------+----------------------+-------------+-------------+--------------------------------------------------+-----------------+
```****

### PR DESCRIPTION
**Pull request by bridadan**
Previously, the filtering logic was pulling out devices that didn't have
a known platform name. This restores the ability to show devices that
don't have known platform name.

Fixes #235

### CODE REVIEW

**Comment by bridadan** [comment]
Probably should have written a test case... I will add that if you agree with the implementation @theotherjimmy

**Comment by theotherjimmy** [comment]
Implementation looks good. Let's have that test!

**Comment by theotherjimmy** [comment]
Through offline discussion, I have agreed to supply the tests.

**Comment by theotherjimmy** [comment]
Looks great!

**Comment by bridadan** [comment]
Thanks for adding the tests @theotherjimmy

**Pull request merged**
