### PR TITLE
[NUCLEO_L031K6] Add target

### PR DESCRIPTION
**Pull request by svastm**

### CODE REVIEW

**Comment by PrzemekWirkus** [comment]
@sg- Sam, is this valid contribution from ST ?

**Comment by PrzemekWirkus** [comment]
@svastm Can you provide information is partner mbed ennoblement team approved this change?

**Comment by sg-** [comment]
This isn't a valid board id for a platform. This board id is used for all ST MCUs under the following conditions:
- target MCU is not identifiable or supported by the version of ST-Link firmware
- target MCU is not attached or powered

I'm sure there are more cases but this ID should be considered a fault state.

**Comment by adustm** [comment]
Hello @PrzemekWirkus and @sg- 
0790 is the ID that we can read on the NUCLEO_L031K6 mbet.htm file with @svastm.
I'll check internally if you have been provided this mcu information.
Cheers
Armelle

**Comment by PrzemekWirkus** [comment]
@sg- mbed-ls is compatible with how Nucleos present their target ID.
We are actually promoting Target ID from mbed.htm first. This allows Nucleo boards to be detected correctly by mbed-ls.

**Comment by svastm** [comment]
`
<html>
<head>
<meta http-equiv="refresh" content="0; url=http://mbed.org/device/?code=07900221461663077952F5AA"/>
<title>mbed Website Shortcut</title>
</head>
<body></body>
</html>`

According to Sylvain Chavagnat the mismatch target ID is 0799.

**Comment by PrzemekWirkus** [comment]
@svastm mbed.htm looks good, I've added simple unit tests [here](https://github.com/ARMmbed/mbed-ls/pull/73/files) to show that Target Id (value ```0790```) will be correctly read from HTM data.

**Comment by sg-** [comment]
0799 is the unknown ID. 0790 is valid. Sorry for the confusion.

**Comment by PrzemekWirkus** [comment]
Thank you! :)

**Pull request merged**
