### PR TITLE
[STM] add B96B_F446VE board

### PR DESCRIPTION
**Pull request by adustm**
Hello, could you please add the B96B_F446VE platform, please ?
Cheers
Armelle

### CODE REVIEW

**Comment by PrzemekWirkus** [comment]
@sg- Please check this platform and let us know if it can be merged!

**Comment by adustm** [comment]
Hello, this platform has been available on mbed for a while. I just realized now that it is not yet available on mbedls.

**Comment by PrzemekWirkus** [comment]
@adustm Yes, it is available already :) I just need to make sure (cross-check with Partner Enablement) that ID to name mapping is correct. It is a simple *two pair of eyes check*.

**Comment by sg-** [comment]
LGTM 👍

**Pull request merged**
