### PR TITLE
Add ublox ODIN-W2 MTB

### PR DESCRIPTION
**Pull request by ashok-rao**
0450 = board ID assigned to new ublox ODIN W2 MTB.

### CODE REVIEW

**Comment by ashok-rao** [comment]
@theotherjimmy  @bridadan .. Could you please review & merge if all OK? Thanks!

**Comment by bridadan** [comment]
@ashok-rao we always do 😄 But if there's a timeline that you need this by please let us know so we can act accordingly. Thanks!

**Comment by ashok-rao** [comment]
Thanks @bridadan . There won't be a platform page for these for now. So, I've not updated the slug. Name is now updated in the DB.

**Comment by ashok-rao** [comment]
Thanks @bridadan . Will await the merge!

**Pull request merged**
