### PR TITLE
Add support for LPC54114 & LPC54608

### PR DESCRIPTION
**Pull request by mmahadevan108**
Signed-off-by: Mahadevan Mahesh <Mahesh.Mahadevan@nxp.com>

### CODE REVIEW

**Comment by mmahadevan108** [comment]
@maclobdell @0xc0170

**Comment by bridadan** [comment]
It looks like the `LPC54114_M0` definition is missing in the mbed database and the entry for the `LPC54114_M4` doesn't seem to quite match that which is listed here. @maclobdell can you take a look?

**Comment by mmahadevan108** [comment]
@bridadan @maclobdell I have changed LPC54114_M4 to LPC54114. I have also included support for LPC54608 in this PR.

**Comment by maclobdell** [comment]
@mmahadevan108  Does the interface firmware enumerate two separate mass storage device drivers - one for each core?  We allocated 1054 for this platform.  1055 is available and we can allocate it too, but I want to confirm if to unique IDs are needed.   Thanks.

**Comment by bridadan** [comment]
@maclobdell not sure what our convention is regarding how entries in the database match with the mbed-ls listing. The names in mbedls don't match any entries in the database at the moment, is this a requirement?

**Comment by maclobdell** [comment]
@bridadan it should match.  Looks like https://github.com/ARMmbed/mbed-os/pull/4290 has been updated so it matches.   This platform has two targets, one for each core.

**Comment by mmahadevan108** [comment]
It enumerates as 1. Initially I thought I would make it as 2 separate devices.

**Comment by maclobdell** [comment]
the updates match the system.  I approve.  

Thanks.

**Pull request merged**
