### PR TITLE
DISCO_L072CZ_LRWAN1 : Add new target

### PR DESCRIPTION
**Pull request by arostm**
This is a new target to be added on mbed.

### CODE REVIEW

**Comment by arostm** [comment]
Hi, when do you plan to merge it ?

**Comment by bridadan** [comment]
cc @mazimkhan @adbridge

**Comment by mazimkhan** [comment]
@bridadan is the platform in DB?

**Comment by bridadan** [comment]
@mazimkhan yup! If I approve PRs it's because I've already checked the DB and made sure it's listed.

**Pull request merged**
