### PR TITLE
Add UNO_91H to the list of boards

### PR DESCRIPTION
**Pull request by RdaZhongyao**
Add new platform "UNO_91H", which is from RDA micro, Ltd.

### CODE REVIEW

**Comment by mazimkhan** [comment]
@screamerbg please confirm change.

**Comment by mazimkhan** [comment]
@maclobdell Can you please check this target.

**Comment by adbridge** [comment]
bump @maclobdell

**Comment by maclobdell** [comment]
sorry for the delay.  thanks for the bump.  I confirm that the platform has been added and assigned unique ID "8001", so it is good to go.  This can be merged. 

@Eric-Yang-China

**Pull request merged**
