### PR TITLE
Add NUCLEO_F042K6 detection

### PR DESCRIPTION
**Pull request by jeromecoutant**

### CODE REVIEW

**Comment by jeromecoutant** [comment]
Hi

Here is MBED.HTM file:

```
<!-- mbed Platform Website and Authentication Shortcut -->
<html>
<head>
<meta http-equiv="refresh" content="0; url=http://mbed.org/device/?code=07850221786077154724E1AD"/>
<title>mbed Website Shortcut</title>
</head>
<body></body>
</html>
```

**Comment by PrzemekWirkus** [comment]
@sg- Please review :)

**Comment by sg-** [comment]
👍

**Comment by PrzemekWirkus** [comment]
After merging  #80 this PR has conflicts, i will merge manually and release `mbed-ls`.

**Comment by PrzemekWirkus** [comment]
@jeromecoutant I've [merged manually](https://github.com/ARMmbed/mbed-ls/commit/e4c643851f018f0b3a664c7b8b59d416eeaaef57) this PR so you do not have to rebase.

**Pull request closed without merging**
