### PR TITLE
Add NUCLEO_F446ZE detection

### PR DESCRIPTION
**Pull request by LMESTM**
Adding this new board ID

### CODE REVIEW

**Comment by PrzemekWirkus** [comment]
@sg- Please review this platform!

**Comment by sg-** [comment]
👍

**Comment by PrzemekWirkus** [comment]
@LMESTM @sg- I've released updated mbed-ls to PyPI: https://pypi.python.org/pypi/mbed-ls/0.2.10
To update to latest please:
```
$ pip install mbed-ls -U
```

**Comment by LMESTM** [comment]
@PrzemekWirkus  THX

**Pull request merged**
