### PR TITLE
Release Version 1.5.0

### PR DESCRIPTION
**Pull request by theotherjimmy**
# Features
 * Add `--update` option to update platform database from the public
 database at os.mbed.com

 # Fixes
 * Silence pesky warnings about implementation details (Warning ->
 Debug)
 * Add a warning if a device is not in the platform database

 # New targets
 * NRF51_DK

### CODE REVIEW

**Comment by theotherjimmy** [comment]
@jupe You get more than you bargained for.

**Comment by jupe** [comment]
Please add PR links to actual release notes - would be easier to see actual PR’s in release

**Comment by jupe** [comment]
and dont forget mention about https://github.com/ARMmbed/mbed-ls/pull/335 :)

**Comment by bridadan** [comment]
@theotherjimmy can you remove the `--update` command from this release? I'd like to sync up with the web folks on this before and make sure we're not doing anything wonky.

**Comment by theotherjimmy** [comment]
@bridadan Yes. Just a moment.

**Comment by theotherjimmy** [comment]
Without the update command this should be 1.4.5 instead.

**Pull request closed without merging**
