### PR TITLE
Add support for LPC55S69

### PR DESCRIPTION
**Pull request by mmahadevan108**
Signed-off-by: Mahesh Mahadevan <mahesh.mahadevan@nxp.com>

### CODE REVIEW

**Comment by mmahadevan108** [comment]
cc @maclobdell @bridadan

**Review by bridadan — COMMENTED** [review]
This is currently entered into the Mbed database as `LPC55S6X`, is that intentional?

**Comment by mmahadevan108** [comment]
Can we change the entry in the mbed database to LPC55S69?

**Comment by bridadan** [comment]
Sure, @maclobdell and/or @ashok-rao are the usual folks to contact about that.

**Comment by mmahadevan108** [comment]
@bridadan The mbed database has been updated by @maclobdell

**Review by bridadan — APPROVED** [review]
Looks great, thanks very much!

**Pull request merged**
