### PR TITLE
MAX326xx

### PR DESCRIPTION
**Pull request by jeremybrodt**
Adding new Maxim Integrated platforms.

### CODE REVIEW

**Comment by mazimkhan** [comment]
@screamerbg Please review target Ids.

**Comment by jeremybrodt** [comment]
@screamerbg Any activity on this?

**Comment by bridadan** [comment]
@jeremybrodt In the online database I'm seeing the board with the product code `0409` not being listed as `MAX32625MBED`. It's under a different name, has the board been renamed recently? Or is this a brand new board? We can take this discussion offline if need be too.

**Comment by jeremybrodt** [comment]
@bridadan I think I got it straight now. Let me know if this still doesn't match the list you have.

**Comment by bridadan** [comment]
@jeremybrodt Everything looks good now except for the `MAX32625MBED` board. It looks like `0410` is the product code for the [Espotel LoRa Module](https://developer.mbed.org/platforms/Espotel-ELMO/) according to our database. Do you have any input on this @maclobdell?

**Comment by jeremybrodt** [comment]
Ok. I have corrected it.

**Comment by mazimkhan** [comment]
@maclobdell can you please reply to Brian's comment.

**Comment by maclobdell** [comment]
Looks good. Please merge.

**Pull request merged**
