### PR TITLE
added platform SILICA_SENSOR_NODE

### PR DESCRIPTION
**Pull request by rspelta**
cc @MarceloSalazar 
Hello, this is a request to add the SILICA_SENSOR_NODE device

### CODE REVIEW

**Comment by MarceloSalazar** [comment]
@mazimkhan FYI

**Comment by mazimkhan** [comment]
@bridadan @maclobdell can you please review this new board.

**Comment by MarceloSalazar** [comment]
FYI I have this board and will be sharing with you soon.

**Comment by mazimkhan** [comment]
Restarted Travis build. Will merge after CI status.

**Comment by MarceloSalazar** [comment]
bump

**Pull request merged**
