### PR TITLE
Add NUCLEO_L433RC_P and NUCLEO_F722ZE boards

### PR DESCRIPTION
**Pull request by bcostm**
Add new NUCLEO boards.

### CODE REVIEW

**Comment by theotherjimmy** [comment]
> Note that the NUCLEO_L452RE and NUCLEO_L452RE_P was already added in PR #190 but they disappeared in the master branch. 

This should no longer be the case. Please reopen if I am mistaken.

**Comment by jeromecoutant** [comment]
Hi
Initial goal of this PR was to introduce NUCLEO_L433RC_P :-)

**Comment by bridadan** [comment]
Oh oops! Totally missed that, sorry @jeromecoutant. Can we reopen the PR @theotherjimmy?

**Comment by theotherjimmy** [comment]
> Initial goal of this PR was to introduce NUCLEO_L433RC_P :-)

I'd appreciate having that in text in the PR description or title.

**Comment by theotherjimmy** [comment]
Thanks!

**Comment by bridadan** [comment]
Does look like there's a merge conflict though.

**Comment by bcostm** [comment]
No problem @theotherjimmy 
I have rebased and solve the conflict but now I see only two lines changed. So the title is false...

**Comment by theotherjimmy** [comment]
Thanks bcostm!

**Pull request merged**
