### PR TITLE
Fix Python 3 compatibility issue

### PR DESCRIPTION
**Pull request by scartmell-arm**
- Changed the open() function to include an encoding argument for Python 3 support.

Fixes: python3 compatibility issues #167

### CODE REVIEW

**Comment by theotherjimmy** [comment]
@scartmell-arm I like it. Could you update the readme and the travis config to mention and test python 2 and 3, respectively?

**Comment by bridadan** [comment]
@mazimkhan @adbridge  For some reason travis isn't running on PRs. Can you please enable this? Should be very simple to enable this from the Travis UI. Thanks!

**Comment by bridadan** [comment]
So even though Travis isn't running at the moment, Python 3.4 is enabled in Travis now: https://github.com/ARMmbed/mbed-ls/blob/master/.travis.yml#L4

@theotherjimmy @scartmell-arm Perhaps we should add later versions of Python 3.x as well? Is that necessary?

**Comment by theotherjimmy** [comment]
> perhaps we should add later versions of Python 3.x as well?

Agreed

> Is that necessary?

We should try to test with the most recent version in Ubuntu.

**Comment by scartmell-arm** [comment]
Np.

> Is that necessary?

It's probably not necessary, but the test runs quick enough that there's no reason not to.

> We should try to test with the most recent version in Ubuntu.

The latest version of python3 is 3.6.x. The current and LTS releases of Ubuntu use 3.5.x and the next release in October will be 3.6.x.

**Comment by mazimkhan** [comment]
Some how the repo was not active on travis. Activated it now. But it may only trigger with another push.

**Comment by bridadan** [comment]
@mazimkhan Might also activate if you close and reopen the PR?

**Comment by theotherjimmy** [comment]
Nailed it. We have all pythons passing. @mazimkhan Merge please?

**Pull request merged**
