### PR TITLE
add manufacture id for EV_COG_AD3029LZ and EV_COG_AD4050LZ

### PR DESCRIPTION
**Pull request by li-ho**

### CODE REVIEW

**Comment by li-ho** [comment]
Leave a comment

**Comment by theotherjimmy** [comment]
@li-ho How could we confirm that these manufacture ids are correct?

**Comment by li-ho** [comment]
ids themselves are correct. You can also confirm with @maclobdell and @sbrewer1

**Comment by maclobdell** [comment]
I can confirm that the IDs are correct on our system.  Looks good to me.  FYI - the mbed partner enablement team handles assigning unique IDs for new platforms and can confirm mbed-ls pull requests.

**Comment by theotherjimmy** [comment]
@maclobdell Thanks for confirmation. 

All: Merging.

**Pull request merged**
